version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 859951689048.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-web-app .
      - docker tag my-web-app:latest 859951689048.dkr.ecr.us-east-1.amazonaws.com/eb_webapp:latest
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"my-web-app","imageUri":"%s"}]' $859951689048D.dkr.ecr.$us-east-1.amazonaws.com/my-web-app:latest > imagedefinitions.json
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 859951689048.dkr.ecr.us-east-1.amazonaws.com/eb_webapp:latest
      - echo Build completed on `date`

artifacts:
  files:
    - imagedefinitions.json
